services:
  app:
    image: ${DOCKER_REGISTRY}/dashboard:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-dashboard
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_THEGRAPH_API_KEY=$NEXT_PUBLIC_THEGRAPH_API_KEY
    ports:
      - '3012:3000'
    networks:
      - traefik-realt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard-${DOCKER_BRANCH}.rule=Host(`dashboard.${DOCKER_BRANCH}.realt.community`)'
      - 'traefik.http.routers.dashboard-${DOCKER_BRANCH}.entrypoints=websecure'
    restart: always

networks:
  traefik-realt:
    external: true
