version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMUNITY_API_KEY_ARG: $COMMUNITY_API_KEY
    ports:
      - '3012:3000'
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-preprod.rule=Host(`dashboard.preprod.realt.community`)"
      - "traefik.http.routers.dashboard-preprod.entrypoints=websecure"
    restart: always

networks:
  traefik-realt:
    external: true
