version: '3'

services:
  app:
    image: registry.realt.community/realtdashboard_prod:latest
    container_name: realtdashboard_prod
    env_file:
    - .env
    ports:
      - '3013:3000'
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-preprod.rule=Host(`dashboard.realt.community`)"
      - "traefik.http.routers.dashboard-preprod.entrypoints=websecure"
    restart: always

networks:
  traefik-realt:
    external: true
